<a href="https://colab.research.google.com/github/Manshisingh03/All-LCA-program/blob/main/assignment_4(a).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:

import numpy as np
A = np.array([[1,2,3],
             [4,5,6]])
B = np.array([[7,8,9],
             [1,2,3]])
C = A + B

print("Matrix A:")
print(A)

print("Matrix B:")
print(B)

print("Addition of two matrix:")
print(C)

Matrix A:
[[1 2 3]
 [4 5 6]]
Matrix B:
[[7 8 9]
 [1 2 3]]
Addition of two matrix:
[[ 8 10 12]
 [ 5  7  9]]
