In [6]:
print("student name:",'manshi')
print("address:",'patna')
print("contact no.:",9900000089)
print("mother tongue:",'hindi')
print("school_name:",'st.pauls high school')
print("year:",2023)
print("panel:",'xyz')
print("roll_no.:",38)


student name: manshi
address: patna
contact no.: 9900000089
mother tongue: hindi
school_name: st.pauls high school
year: 2023
panel: xyz
roll_no.: 38


In [7]:
student name =["ram","shyam","rohan"]
roll_no =[3,4,5]
marks=["physics:"67,78,93,
       "maths:"34,57,95,
       "chemistry:"67,45,86]
percentage= physics+maths+chemistry/300*100
print(percentage)


SyntaxError: invalid syntax (881199033.py, line 1)

In [11]:
num = float(input("enter a number: "))
if num>0:
        print("number is positive")
elif num<0:
        print("number is negative")
else:
        print("zero")

enter a number:  9


number is positive


In [15]:
num = int(input("enter a number: "))
if  num % 2 == 0:
          print("even number")
else:
    print("odd number")

enter a number:  9


odd number


In [17]:
a =56
b =46
if a % 10 == b % 10:
    print("true")
else:
    print("false")

true


In [22]:
for i in range(1,11):
    print(i,end="\t")

1	2	3	4	5	6	7	8	9	10	

In [23]:
for i in range(24,58,2):
    print(i)

24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56


In [1]:
num  = 3
if num <= 1:
    print("not a prime number")
else:
    for i in range(2,num):
        if num%i==0:
            print("not a prime number")

            break
        else:
            print("prime number")

prime number


In [4]:
for num in range(10,100):
    if num > 1:
        for i in range(2,num):
            if num % i==0:
                break
            else:
                print(num, end=" ")

11 11 11 11 11 11 11 11 11 13 13 13 13 13 13 13 13 13 13 13 15 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 21 23 23 23 23 23 23 23 23 23 23 23 23 23 23 23 23 23 23 23 23 23 25 25 25 27 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 33 35 35 35 37 37 37 37 37 37 37 37 37 37 37 37 37 37 37 37 37 37 37 37 37 37 37 37 37 37 37 37 37 37 37 37 37 37 37 39 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 43 43 43 43 43 43 43 43 43 43 43 43 43 43 43 43 43 43 43 43 43 43 43 43 43 43 43 43 43 43 43 43 43 43 43 43 43 43 43 43 43 45 47 47 47 47 47 47 47 47 47 47 47 47 47 47 47 47 47 47 47 47 47 47 47 47 47 47 47 47 47 47 47 47 47 47 47 47 47 47 47 47 47 47 47 47 47 49 49 49 49 49 51 53 53 53 53 53 53 53 53 53 53 53 53 53 53 53 53 53 53 53 53 53 53 53 53 53 53 5

In [5]:
num=34
sum=0
while num>0:
    digit = num%10
    sum=sum+digit
    num=num//10

    print("sum of digit=",sum)

sum of digit= 4
sum of digit= 7


In [6]:
num=78
reverse =0

while num>0:
    digit=num%10
    reverse=reverse*10+digit

    num = num//10

print("reverse = ",reverse)

reverse =  87


In [10]:
num = 9090
original=num
reverse=0

while num>0:
    digit = num%10
    reverse=reverse*10+digit
    num=num//10
if original == reverse:
    print("palindrome number")
else:
    print("not a palindrome number")

not a palindrome number


In [13]:
for i in range(5):
    num=int(input("enter the number"))
cube = num**3
print("cube=",cube)

enter the number 2
enter the number 3
enter the number 4
enter the number 5
enter the number 5


cube= 125


In [14]:
num=67

print("prime factor are :")

i=2
while num > 1:
    if num % i == 0:
        print(i,end=" ")
        num=num//i
    else:
        i=i+1

prime factor are :
67 

In [17]:
print("*")
print("**")
print("***")
print("****")

*
**
***
****


In [18]:
print("     *   ")
print("    ***   ")
print("   *****  ")
print("  *******   ")

     *   
    ***   
   *****  
  *******   


In [ ]:
                                                                    numpy

In [20]:
import numpy as np
arr =np.linspace(5,50,10)
print(arr)


[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [21]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [22]:
import numpy as np
arr1= np.array([1,2,3])
arr2=np.array([4,5,6])
print(arr1+arr2)
print(arr1-arr2)

[5 7 9]
[-3 -3 -3]


In [26]:
import numpy as np
arr1= np.array([1,2,3])
arr2=np.array([4,5,6])

dot_product = np.dot(arr1,arr2)
print("dot product=",dot_product)

dot product= 32


In [28]:
import numpy as np
arr=np.array([10,20,30,40,50])

mean=np.mean(arr)
median=np.median(arr)
std=np.std(arr)

print("mean=",mean)
print("median=",median)
print("standard deviation=",std)

mean= 30.0
median= 30.0
standard deviation= 14.142135623730951


In [ ]:
                                                                  sets 

In [1]:
mysets= {"kiwi","banana","mango","apple"}
mysets.remove("banana")
print(mysets)


{'kiwi', 'mango', 'apple'}


In [9]:
set1={10,20,30,40,50}
set2={10,70,80,90}
intersection=set1.intersection(set2)
print("interesection:",intersection)

interesection: {10}


In [3]:
x = {"kiwi","banana","mango","apple"}
y = {"pikachu","kite","orange"}
z=x.union(y)
print(z)


{'mango', 'pikachu', 'kite', 'kiwi', 'orange', 'banana', 'apple'}


In [6]:
x = {"kiwi","banana","mango","apple"}
print("maximum value:",max(x))
print("minimum value:",min(x))


maximum value: mango
minimum value: apple


In [ ]:
                                                               string

In [11]:
s="MAnshi"

upper=0
lower=0

for ch in s:
    if ch.isupper():
        upper+=1
    elif ch.islower():
        lower+=1

print("uppercase:",upper)
print("lowercase:",lower)

uppercase: 2
lowercase: 4
